### ISSUE TITLE
Subscribers not added to the created list

### ISSUE THREAD

**Issue by bispldeveloper** [statamic-rad-pack/campaign-monitor#10]
### Description

I have a statamic website whose contact form is connected to Campaign Monitor add-on "https://statamic.com/index.php/addons/rad-pack/campaign-monitor", I could do the backend setup and populate the list created. For eg: "Website contact form" is a list created in my campaign monitor account and in the backend I am calling this list for the "contact form" on the website. The frontend form has name, email, telephone and required service and same fields in the backend is populated except for the "required service". There was "consent" enabled initially which I have turned it off as the subscribers were not getting added to the list. But even after disabling it the subscribers are not getting added. I don't know if there are any settings that I need to tweak or any code I need to call for the frontend form. Please help me to resolve this.

### Steps to reproduce

1. Installed campaign monitor on Statamic website
2. Called the API Key and Client ID in ENV file
3. Connected the created list to the contact form via statamic admin panel
4. Next tried to submit that form on frontend and expecting the user details submitted to be added to the created list in campaign monitor.
5. I have also called the list ID in ENV file.

### Environment

There is no error shown but list is blank though the form was submitted several times

**Comment by bispldeveloper** [comment]
I got the problem.. it was the telephone number format. If I give +44 continued with the number it will work.

**Comment by ryanmitchell** [comment]
Great, can i close this then?
